Voting Documentation
digicatapult/dscp-node pull request #69
Opened 2022-06-27 13:33 UTC by nitro-marky

Documents the process of voting and how to remove someone's voting rights.

2022-06-27 13:46 UTC, dblane-digicatapult requested changes

2022-06-27 13:46 UTC, dblane-digicatapult commented on governance.md
> +<img width="720" alt="Screenshot 2022-06-27 at 14 14 08" src="https://user-images.githubusercontent.com/35331926/175950487-0765eb54-d8a0-4fe6-adbb-9dd62653b39a.png">
Look at how we include images in other [repositories](https://raw.githubusercontent.com/digicatapult/wasp-documentation/main/docs/architecture.md)

2022-06-28 08:54 UTC, n3op2 approved these changes
quite a few commits for such a little change 🤔

2022-06-28 08:57 UTC, nitro-marky commented
It was just to keep track of the images being added. I'm following Darryl's school of commits 😄

2022-06-28 10:09 UTC, jonmattgray approved these changes

2022-06-28 10:16 UTC, dblane-digicatapult approved these changes

2022-06-28 10:17 UTC, merged