Update deprecated actions
digicatapult/dscp-node pull request #92
Opened 2022-10-24 17:09 UTC by jonmattgray

See reduced number of annotations https://github.com/digicatapult/dscp-node/actions/runs/3321131708. 
`rustup` and `cargo` actions still use node 12 for now [ticket](https://digicatapult.atlassian.net/browse/IN-401)
Explanation for remaining warnings https://github.com/digicatapult/dscp-api/pull/60

2022-10-26 13:42 UTC, dblane-digicatapult requested changes

2022-10-26 13:42 UTC, dblane-digicatapult commented on node/Cargo.toml
> +dscp-node-runtime = { path = '../runtime', version = '4.3.2' }
```suggestion
dscp-node-runtime = { path = '../runtime', version = '4.4.1' }
```

2022-10-28 11:20 UTC, dblane-digicatapult approved these changes

2022-10-28 13:17 UTC, n3op2 approved these changes

2022-10-28 13:48 UTC, merged